const getters = {
  tag: state => state.tags.tag,
  language: state => state.common.language,
  website: state => state.common.website,
  userInfo: state => state.user.userInfo,
  tenantId: state => state.user.tenantId,
  subStation: state => state.user.subStation,
  colorName: state => state.common.colorName,
  themeName: state => state.common.themeName,
  fontSize: state => state.common.fontSize,
  isShade: state => state.common.isShade,
  isCollapse: state => state.common.isCollapse,
  keyCollapse: (state, getters) => getters.screen > 1 ? getters.isCollapse : false,
  screen: state => state.common.screen,
  isLock: state => state.common.isLock,
  isFullScren: state => state.common.isFullScren,
  isMenu: state => state.common.isMenu,
  lockPasswd: state => state.common.lockPasswd,
  tagList: state => state.tags.tagList,
  tagWel: state => state.tags.tagWel,
  token: state => state.user.token,
  roles: state => state.user.roles,
  permission: state => state.user.permission,
  menu: state => state.user.menu,
  menuId: state => state.user.menuId,
  menuApps: state => state.user.menuApps,
  menuAll: state => state.user.menuAll,
  appCode: state => state.user.appCode,
  logsList: state => state.logs.logsList,
  logsLen: state => state.logs.logsList.length || 0,
  logsFlag: (state, getters) => getters.logsLen === 0,
  flowRoutes: state => state.dict.flowRoutes,
  __POWERED_BY_QIANKUN__: state => state.microApps.__POWERED_BY_QIANKUN__,
  dataAuthKey: state => state.user.dataAuthKey
}
export default getters
